# Generated by Django 3.2.7 on 2021-09-04 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_alter_meetup_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='image',
        ),
    ]
