# Generated by Django 3.2.7 on 2021-09-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_remove_meetup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
